# This playbook is going to provision host a so it can launch the app

---
- name: a play to sync over all the app files
  hosts: default
  become: true
  tasks:
  - name: we sync the app/ folder to the host machine
    synchronize:
      src: /home/ubuntu/app
      dest: /home/ubuntu/
# find IP address needed
- hosts: localhost
  connection: local
  tasks:
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_default_ipv4.address

- name: a play to install packages needed
  hosts: default
  # This is targeting host_a and is used to define where this play will run
  become: true
  # Become is used as the root permission to perform tasks that may require admin access
  tasks:
  # This block updates and upgrades all the packages
  - name: update and upgrade packages
    apt: upgrade=yes update_cache=yes

  # This block installs whatever is in the list
  - name: install git and nginx
    apt:
      name:
        - nginx
        - git
      update_cache: yes
      state: present
    notify: fix_nginx_bug

  # This block installs nodejs
  - name: add nodejs apt key
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present
  - name: install nodejs
    apt:
      name: nodejs
      state: present

  # This block makes sure npm installs all and then pm2 installs
  - name: install npm
    apt:
      name: npm
      state: present

  - name: install pm2
    npm:
      name: pm2
      global: yes
      production: yes

- name: a play to set up the reverse proxy
  hosts: default
  become: true
  tasks:
  # This block will copy the reverse proxy over and unlink the default
  - name: copy proxy to conf.d folder
    copy:
      src: /home/ubuntu/app/reverse-proxy.conf
      dest: /etc/nginx/sites-available/reverse-proxy.conf
      remote_src: yes

  # This block will remove the default proxy, link the new one and restart nginx
  - name: remove default proxy
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
  - name: symbolically link the new reverse-proxy
    file:
      src: /etc/nginx/sites-available/reverse-proxy.conf
      dest: /etc/nginx/sites-enabled/default
      state: link
    notify: restart_nginx

  handlers:
    - name: restart_nginx
      service:
        name: nginx
        state: restarted
        